### ISSUE TITLE
32bit unsigned value not supported

### ISSUE THREAD

**Issue by dokechin** [tokuhirom/Acme-Kensiro#2]
I used this module.

print kensiro(1600);

But I got message below.

Character in 'C' format wrapped in pack at /usr/lib/perl5/site_perl/5.14/Acme/Kensiro.pm line 14.

I read source , and Acme::Kensiro is suppting 8bit unsined value.

I hope support 32bit unsigned value.

I changed source below and I think going well.

my $dst = unpack("B32",  pack("L", $src));

**Comment by tokuhirom** [comment]
Patches welcome.

**Comment by tokuhirom** [comment]
@kamipo

**Comment by kamipo** [comment]
@tokuhirom

**Comment by tagomoris** [comment]
@kamipo

**Comment by kamipo** [comment]
@tagomoris

**Comment by sugyan** [comment]
@kamipo

**Comment by kamipo** [comment]
@sugyan

**Comment by kan** [comment]
@kamipo

**Comment by kamipo** [comment]
@kan

**Comment by tokuhirom** [comment]
Fixed by #3
